### ISSUE TITLE
UnhandledRejection: Launching server "phpactor" using command phpactor failed

### ISSUE THREAD

**Issue by GiancarloAparicio** [phpactor/coc-phpactor#12]
When I open a php file I get this error, I have tried to use phpactor with Plug, cocInstall, coc file but in all cases I get that error

![image](https://user-images.githubusercontent.com/61440825/113345439-0fd39000-92f8-11eb-8349-bf4e4738197f.png)
The same thing comes out in messages.
Also completely uninstall neovim but the error persists :(

The versions I use are: 
neovim 0.4.4
nodejs 15.13.0
python 3.7.0

**Comment by dantleech** [comment]
It requires at least PHP 7.3 if that's any help. Can you run `phpactor` from the CLI?

**Comment by GiancarloAparicio** [comment]
@dantleech hello, thank you for taking the time to help me.

As you mentioned, I couldn't use the cli either, silly I used to install the plugins as " Plug 'phpactor/phpactor' " that I didn't read the doc where it clearly says that should be used, " Plug 'phpactor/phpactor', {'for': 'php', 'tag': '*', 'do': 'composer install --no-dev -o'} " 

![image](https://user-images.githubusercontent.com/61440825/113467790-fbcc8300-940a-11eb-99ff-275ea96daf4b.png)

However, after successfully installing phpactor and having the cli, the error persists :(

**Comment by dantleech** [comment]
Maybe `:CocCommand workspace.showOutput phpactor` shows some more useful output? Otherwise you could enable the Phpactor logs https://phpactor.readthedocs.io/en/master/other/developing.html#logging

**Comment by GiancarloAparicio** [comment]
Apparently it was a conflict with some dependencies, the following fix my problem :)

```
apt install php7.4-intl php7.4-curl 
composer require beberlei/assert dantleech/what-changed phpbench/phpbench
```

**Comment by dantleech** [comment]
Oh that's strange -- do you have the exact error message you encountered?

**Comment by GiancarloAparicio** [comment]
I did not save the error message, but what I did was use the phpactor cli from the shell and I got an error where it said that the 3 previous packages were not found and those packages depended on php-intl and php-curl, maybe that's why phpactor could not be installed correctly and I got that error

**Comment by dantleech** [comment]
hm, I can understand if composer said that it required `intl` and `curl` extensions, in which case it's not an "error" (although it can be reported better). But then a `composer install` should have been fine after installing those extensions I guess.
