### ISSUE TITLE
Phpactor. status is not an editor command in nvim.

### ISSUE THREAD

**Issue by kevin1121** [phpactor/coc-phpactor#19]
Phpactor. status is not an editor command in nvim.
How do we solve this?
![image](https://user-images.githubusercontent.com/31364407/147056601-cd05f6ff-d138-481c-8ceb-777a0a6a6603.png)

**Comment by nasrul21** [comment]
I think you used the wrong command. You should call `:PhpactorStatus` instead of `phpactor.status`
@kevin1121
