### ISSUE TITLE
How to access other phpactor features?

### ISSUE THREAD

**Issue by lukepass** [phpactor/coc-phpactor#25]
Hello and **thanks for the good work**! Is there a way to access the more advanced phpactor features such as `transform`, `context menu` etc...?

I mapped these commands:

```
<Plug>(coc-codeaction-cursor)
<Plug>(coc-codeaction-selected)
<Plug>(coc-refactor)
```

But I would like to get the menu such as in "standard" phpactor:

![image](https://user-images.githubusercontent.com/6429961/168825555-c38cae7a-0cf1-4db0-b26a-cfb8409a44b7.png)

Which `<Plug>(coc-XYZ)` should I map?

Thanks!

**Comment by dantleech** [comment]
All of those transformations are available as standard code actions.

But nothing wrong with using the "standard" Phpactor with VIM - I do this to fill in the missing [gaps](https://github.com/phpactor/phpactor/issues/1184):  https://phpactor.readthedocs.io/en/master/usage/vim-plugin.html

**Comment by lukepass** [comment]
Thanks for the quick answer! How can I access those code actions? How can I
see the exact name to call in the mapping? Could you please make an example
for "import all missing classes" and "generate constructor"?

Thanks a lot!

Il mar 17 mag 2022, 20:36 dantleech ***@***.***> ha scritto:

**Comment by dantleech** [comment]
when i used CoC I had:

```
nmap <Leader>ca <Plug>(coc-codeaction)
xmap <Leader>ca <Plug>(coc-codeaction-selected)
```

you just need to invoke this anywhere in the document, if one of the transformations can be applied it will offer you that option.

**Comment by lukepass** [comment]
Yes, I have the same mappings but unfortunately most of the phpactor best features (namely "import all", "transform", "complete constructor" etc...) don't appear in the menu:

![image](https://user-images.githubusercontent.com/6429961/168988816-979c19da-bc25-4fb1-b95a-a4f46612f8fc.png)

**Comment by dantleech** [comment]
many of the "transforms" are now code actions which are shown if they are possible (e.g. complete constructor will show if you have a constructor with no properties or parameter assignments). some exceptions include "generate interface" which is still not supported as a code action.

Import all should show as a code action. 

closing for now, but feel free to carry on the discussion

**Comment by lukepass** [comment]
Thank you @dantleech ! Now it's a lot better!

This is the "classic" menu:

![image](https://user-images.githubusercontent.com/6429961/178935160-ca38b837-e0e0-4574-a7c1-7676fe038831.png)

These are the new menus:

![image](https://user-images.githubusercontent.com/6429961/178935236-1c5faf7f-2345-473f-a45b-a8ca7415e554.png)

![image](https://user-images.githubusercontent.com/6429961/178935254-3e6f447d-5a1e-4653-a978-c79f4eb02e75.png)

It seems that the appropriate context-menu appears only when needed, which is even better!

**Comment by dantleech** [comment]
awsome!
