### ISSUE TITLE
Symbol discovery

### ISSUE THREAD

**Issue by rosmanov** [phpactor/coc-phpactor#5]
It would be awesome if you could implement symbol discovery feature as in https://github.com/marlonfan/coc-phpls/

**Comment by dantleech** [comment]
What does it do?

**Comment by rosmanov** [comment]
@dantleech , it desponds to `:CocList -I symbols` command. I think it should be https://microsoft.github.io/language-server-protocol/specification#workspace_symbol

**Comment by dantleech** [comment]
that _should_ be low-hanging fruit :)

**Comment by dantleech** [comment]
I actually thought this was _document_ symbols (`CocList outline`) which was pretty easy and implemented now in `develop`.

`CocList -I symbols` is _workspace_ symbols - which is a bit more tricky, but still should be doable ...

**Comment by dantleech** [comment]
this has been basically implemented
