### ISSUE TITLE
duplicates symbol $

### ISSUE THREAD

**Issue by vivoconunxino** [phpactor/coc-phpactor#6]
Hi @dantleech, whenever I try to autocomplete a variable with the coc-phpactor extension it duplicates the $ symbol.

For instance, 

`$myv<c-o><c-u>` will turn into `$$myvariable`

- If I start nvim without the extension enabled and then I enable such extension it does not happen.
- If I start nvim with the extension enabled and then I disable and enable it again it does not happen.
- If I start nvim with the extension enabled then it happens.

**Comment by dantleech** [comment]
Does https://phpactor.readthedocs.io/en/develop/lsp/vim.html#two-dollars-on-variables help?

**Comment by vivoconunxino** [comment]
Totally, I even had it added on the .phpactor.yml settings for another project, two weeks on holidays and there we are...

I feel so ashamed, thanks

**Comment by dantleech** [comment]
To be fair it's probably wrong by default, seems it can go either way depending on the environment.
